application: encuestainkafarma
version: 3
runtime: python27
api_version: 1
threadsafe: true

builtins:
- appstats: on
- remote_api: on

handlers:

- url: /assets
  static_dir: assets
  
- url: /favicon.ico
  static_files: assets/img/favicon.ico
  upload: assets/img/favicon.ico
  
- url: /.*
  script: main.application

  
libraries:
- name: jinja2
  version: "2.6"
